language: android
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: eYDrmtbB1tQVz9FmtmMjmOWDTLkasfaZifygR0eD2z9e36HWMAJxSW9TungtUEwQMwI/fsyw8ZuFmky0aKVk2IE81lQkHghBg0Ws7WhKYYxKZ1Rh0HhlMVMeWl94d1Q9uVzs0JPPXT9blauiBeDuV4FRDa9LxZXWQY+yB0LWNAQ8Aaoj4jhG4HBNcrteMqv0BL7gb0wVkjM+57DUOkR0K6A1swPHhf/onI/A8js4so1Q6pRCY2Zdj0kwK1Z37auWaohPx9J05t7EGF/5p+P9thdy1HH2crs/SVI4zJGU/5P5WDI6jvf6jWWz7iKCDL5cPR9gpTSb1DCFxV/xbDUrJ97jAo61S6al7tw4nPsyGsSVVQKF0WdsqqpQDmao6MmvbdaibPcMAaw3K5XLeoPa7LJ+OdP4qGscJ1JGEXBb3fbVhEvV0DJQk8IDueZr2pshO/K8TNuUUNH11FJj4zg4luaeeQdLlSmMqlPPuQfQFNZHjDjKMj82STwd80MDTWddYaUutZQt9ScI7wouYGg8SUeR5Uwa2X5RBWEg2coeLS34GWnnfc0cb63hjnZLktTOya69lFtlNIWC+PqEJT65RqL/A2/t2/B4oU859MT9g5QWe5YVgM3YIPJm+E/E/jKdyu5aSmbPwtiL18P0e13xDrl6jZo89E38HiBAMfgqo6Y=
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  all_branches: true
  on:
    tags: true